BUG-73517 Sqoop Jobs failing on HDP 2.5 due to java.lang.NoClassDefFoundError: org/json/JSONObject
Change-Id: I3798169520a3e01f3cca451bc5b76d5c3efba7db