HOTFIX-861 BUG-80631 SQOOP-3159 (SQOOP-3160): Sqoop (export + --table) with Oracle table_name having '$' fails with error (ORA-00942 or java.lang.NoClassDefFoundError)
(Szabolcs Vasas via Anna Szonyi)

(cherry picked from commit afd6a8610e8ac4291e52c2c167fe7b8d6f706be8)

Change-Id: I37bff9425b31290e28b4d282c9c938f49af7b6db
(cherry picked from commit 79e39c44ba26d7b883ce966d466bcefd117c3bf2)